(function () {
  var edi, feed, jQuery, load_css, twitter;
  require.config({
    baseUrl: '.',
    paths: { jquery: 'scripts/libs/jquery/jquery-2.0.3' }
  });
  load_css = function (url, _) {
    var link;
    link = document.createElement('link');
    link.type = 'text/css';
    link.rel = 'stylesheet';
    link.href = url;
    document.getElementsByTagName('head')[0].appendChild(link);
    return _(true);
  };
  jQuery = '';
  edi = '';
  twitter = '';
  require([
    'jquery',
    'scripts/libs/edijson_jquery/edijson',
    'scripts/libs/twitter_bootstrap/js/bootstrap'
  ], function () {
    jQuery = arguments[0];
    edi = arguments[1];
    twitter = arguments[2];
    console.dir(edi);
    feed = 2;
    load_css('bla', function () {
      feed = arguments[0];
      alert(feed);
    });
  });
}.call(this));
/* Generated by Continuum.js v0.0.2 */
//@ sourceMappingURL=index.js.map